[tool.poetry]
name = "humming_bot_graph"
version = "0.1.0"
description = ""
authors = ["Yanis"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
